### ISSUE TITLE
Masterpages not working? (hyperfastcgi 2 + nginx + unix socket)

### ISSUE THREAD

**Issue by tekhedd** [xplicit/HyperFastCgi#22]
I seem to have run into a problem with HFC and compiled master page cache. I am using the latest trunk (compiled in docker vs mono 3.12) which is exactly equal to the current v0.3 stable. 

When I load my site-with-masterpages with HFC, the first page loaded displays correctly. The remaining pages show correct titles and updated header fields, but every page loaded displays the same content for the asp:Content chunk. (If the first page loaded is a redirect after login, the app goes into a redirect loop because every response is the same as the initial redirect.) I have snooped the socket using socat and the request is definitely for the correct page, while the response is as I describe.

Another thing that seems to indicate a caching issue is that if I create new pages by "cp index.aspx index2.aspx", the first copy I create loads correctly, and then more copies that I create sometimes display the same as the first copied page, and sometimes do not.

Site has been working in IIS and xsp2 for years. Works in mono-fastcgi-server2 using the same running instance of nginx (no changes to the nginx configuration when comparing mono-fastcgi vs hyperfastcgi), Between that and the socat snooping, I do not think there is any issue at the nginx level.

I will try to reproduce the problem with a minimal example.

**Comment by xplicit** [comment]
Please, check the following:
- if you use `keepalive` mode in nginx, then you pass this options in command line to hyperfastcgi v0.3.
- did you pass `/addtrailingslash=true` option to hyperfastcgi?
- check  that you correcly configure `fastcgi_params' `PATH_INFO` and `SCRIPT_FILENAME` look this issue for more info. https://github.com/xplicit/HyperFastCgi/issues/21

If you think that all is configured properly, than the project which is reproduced this issue will be usefull

**Comment by tekhedd** [comment]
Thank you, I tried all of these just now (and tried turning off keepalives in nginx as well). I am using a configuration copy/pasted from issue #21 actually. :) 

I'll see if I can reproduce the problem with a minimal test case.

**Comment by tekhedd** [comment]
OK, I have removed pretty much all of the code except for the template and three pages, and some config files. Funky, it doesn't happen if the files are just dropped in the same directory.

http://tekhedd.com/wp-content/uploads/test.tar.gz

Unpack it to /tmp/, oh and you'll have ot update the unix socket location, or change socket types. Oops. I'd be very interested to see if the problem can be reproduced on other systems.

**Comment by xplicit** [comment]
I think the issue in wrong configuration of `web-aplication` section. Change path from '.' to absolute path to your web site. This should help. 

By the way I would recommend to use native listener instead of managed, because ManagedTransport is slow (due to mono remoting sloweness) and tested much less than native transport.

**Comment by tekhedd** [comment]
So a relative path to the application root, relative to "root" is the issue? Argh, it does. My app had two apps both located in relative paths beneath "root". Ye gods, what a waste of two days.

OK, so the bug should be named "using relative paths for application root results in errors in master pages". I thought the whole point of "root" was to set the base location, as in xsp and the various mono tools. Grrr.

Apparently the application paths in the config file are relative to cwd instead of "root" as well. So, er, that's probably related, and definitely a bug. Thought the whole point was that 

:(   As it turns out we're going to be moving to self-hosting anyway, but glad I could contribute some testing. have a good one.

**Comment by xplicit** [comment]
I'll look into it. From what I see there are two issues: 
- server root is not set correctly
- (what is much worse) there is a possible cross-domain call to get the server root path for every http request.
