### ISSUE TITLE
How to install newer version?

### ISSUE THREAD

**Issue by cvetomirtodorov** [xplicit/HyperFastCgi#27]
Question: I have an older version of HFCGI. I'd like to update it with the latest stable. What commands do I run?

**Comment by xplicit** [comment]
You should run the same commands as you just want to install new version. Please note that HyperFastCgi 0.4 requires new config file and command line parameters differ from v0.3, so you have to edit config file (which can be found in `samples` directory)  and pass it to HyperFastCgi

**Comment by cvetomirtodorov** [comment]
Actually I started using 0.3 as the readme says it is the latest stable version. Then I saw in the roadmap that the features for 0.4 are implemented already. So I'm considering checking it out.

Anyway thanks for your answer and the fact you're working on this project!
