### ISSUE TITLE
HyperFastCgi Performace Degradation

### ISSUE THREAD

**Issue by matsaleh13** [xplicit/HyperFastCgi#28]
Hello, 
I've been evaluating HyperFastCgi in the hope it will improve performance compared to the stock Mono implementation. Your excellent blog series (http://forcedtoadmin.blogspot.com/2013/11/servicestack-performance-in-mono-p1.html) encouraged me to try HFC. 

Unfortunately, I've encountered severe performance degradation after a short while during testing with ApacheBench. 

The following test URL is handled by our webapp, which simply responds by echoing the string from the last path segment (i.e. "test"). 
```bash
ab -kc 20 -t 360 http://internal-ec2-instance.mycompany.com/helloworld/api/hello/echo/test
```
The table below shows the degradation over several test runs:

Test Run | Requests | Time (sec) | Requests/Second | CPU %
------------ | ------------- | ------------- | ------------- | -------------
1 | 50000 | 102.760 | 486.57 | ~165%
2 | 50000 | 94.819 | 527.32 | ~165%
3 | 50000 | 133.470 | 374.62 | ~135%
4 | 50000 | 180.357 | 277.23 | ~40-80%
5 | 49988| 360.012 | 138.85 | ~0-50%
6 | 2963| 360.022 | 8.23 | ~0-8%

The helloworld test service was started fresh before test 1, and not restarted between tests.

Note that as performance degraded, CPU utilization by the HyperFastCgi process decreased, so it doesn’t appear to be CPU bound.

Also, periodically while running these tests, I checked open connections owned by mono using: 
```Shell 
sudo netstat -ap | grep mono | wc –l
```
The highest value I got during a test was 84, and usually was closer to 40-50. I actually think that seems low, but at least it seems to show that connections aren’t being left open unnecessarily.

The test above was run with mono –debug; however, other tests were run without this flag, with very similar performance results. Without –debug, it took a little while longer for the degradation to show up, and the lowest measured throughput was ~26 requests/sec (compared to ~8 with –debug). CPU utilization was the same, but there was slightly lower memory utilization by the HFC process.

I’ve observed similar behavior with various HFC and Nginx configurations, but for the tests above I used the following configs. 

HFC (helloworld.config):
```XML
<configuration>
        <server type="HyperFastCgi.ApplicationServers.SimpleApplicationServer">
                <!-- Host factory defines how host will be created. SystemWebHostFactory creates host in AppDomain in standard ASP.NET way -->
                <host-factory>HyperFastCgi.HostFactories.SystemWebHostFactory</host-factory>
                <!-- <threads> creates threads at startup. Value "0" means default value -->
                <threads min-worker="40" max-worker="0" min-io="4" max-io="0" />
                <!--- Sets the application host root directory -->
                <!-- <root-dir>/path/to/your/dir</root-dir> -->
        </server>
        <listener type="HyperFastCgi.Listeners.NativeListener">
                <apphost-transport type="HyperFastCgi.Transports.NativeTransport" />
                <protocol>Unix</protocol>
                <address>/tmp/helloworld</address>
        </listener>
    <apphost type="HyperFastCgi.AppHosts.AspNet.AspNetApplicationHost">
                <log level="Debug" write-to-console="true" />
                <add-trailing-slash>false</add-trailing-slash>
    </apphost>
    <web-applications>
        <web-application>
                <name>HelloWorld.Web</name>
                <vhost>internal-ec2-instance.mycompany.com</vhost>
                <vport>80</vport>
                <vpath>/helloworld</vpath>
                <path>/opt/mycompany/HelloWorld/HelloWorld.Web</path>
        </web-application>
    </web-applications>
</configuration>
```

Nginx Configs:

/etc/nginx/nginx.conf
```Nginx
user www-data;
worker_processes 4;
pid /var/run/nginx.pid;

events {
        worker_connections 768;
        multi_accept on;
}

http {

        ##
        # Basic Settings
        ##

        sendfile on;
        tcp_nopush on;
        tcp_nodelay on;
        keepalive_timeout 65;
        types_hash_max_size 2048;
        # server_tokens off;

        # server_names_hash_bucket_size 64;
        # server_name_in_redirect off;

        include /etc/nginx/mime.types;
        default_type application/octet-stream;

        ##
        # Logging Settings
        ##

        access_log /var/log/nginx/access.log;
        error_log /var/log/nginx/error.log;

        ##
        # Gzip Settings
        ##

        gzip on;
        gzip_disable "msie6";

        # gzip_vary on;
        # gzip_proxied any;
        # gzip_comp_level 6;	
        # gzip_buffers 16 8k;
        # gzip_http_version 1.1;
        # gzip_types text/plain text/css application/json application/x-javascript text/xml application/xml application/xml+rss text/javascript;

        ##
        # Virtual Host Configs
        ##

        include /etc/nginx/conf.d/*.conf;
        include /etc/nginx/sites-enabled/*;
}
```

Included via /etc/nginx/sites-enabled/*;
```Nginx
upstream fastcgi_backend {
  server unix:/tmp/helloworld;
  keepalive 32;
}

server {
  listen 80 default_server;
  listen [::]:80 default_server ipv6only=on;

  include /etc/nginx/locations/*;
  include /opt/mycompany/nginx/fastcgi_common_params;
}
```

Included via /etc/nginx/locations/*;
```Nginx
  location /helloworld {
    fastcgi_pass fastcgi_backend;
    fastcgi_keep_conn on;
  }
```

Included via /opt/mycompany/nginx/fastcgi_common_params;
```Nginx
fastcgi_param  QUERY_STRING        $query_string;
fastcgi_param  REQUEST_METHOD      $request_method;
fastcgi_param  CONTENT_TYPE        $content_type;
fastcgi_param  CONTENT_LENGTH      $content_length;
fastcgi_param  SCRIPT_NAME         $fastcgi_script_name;
fastcgi_param  REQUEST_URI         $request_uri;
fastcgi_param  DOCUMENT_URI        $document_uri;
fastcgi_param  DOCUMENT_ROOT       $document_root;
fastcgi_param  SERVER_PROTOCOL     $server_protocol;
fastcgi_param  GATEWAY_INTERFACE   CGI/1.1;
fastcgi_param  SERVER_SOFTWARE     nginx/$nginx_version;
fastcgi_param  REMOTE_ADDR         $remote_addr;
fastcgi_param  REMOTE_PORT         $remote_port;
fastcgi_param  SERVER_ADDR         $server_addr;
fastcgi_param  SERVER_PORT         $server_port;
fastcgi_param  SERVER_NAME         $server_name;
fastcgi_param  HTTPS               $https if_not_empty;
fastcgi_param  PATH_INFO           "";
fastcgi_param  SCRIPT_FILENAME     $document_root$fastcgi_script_name;
```

We’re executing HFC as a service via init.d script. In the script, we call HFC as follows (helloworld.config is the HFC config file above):
```Shell
    sudo -u serviceuser -E hyperfastcgi4
    /config=/opt/mycompany/nginx/hyperfastcgi/helloworld.config
    /keepalive=true
    /logfile=/var/log/mycompany/hyperfastcgi_helloworld.log
    /loglevels=All
    /printlog=True
```

My test system is an EC2 m3.large instance running Ubuntu 12.4. The ApacheBench tests were executed on another, separate EC2 instance. 

Our Mono version:
```Shell
Mono JIT compiler version 3.12.1 (tarball Fri Mar  6 19:12:47 UTC 2015)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug
	LLVM:          supported, not enabled.
	GC:            sgen
```

I built HyperFastCgi 0.4 from master, compiled with autogen.sh --prefix=/usr, then make and make install.

As a baseline, I ran ApacheBench at 500 concurrency to fetch a static page served by Nginx from the same host:

```Shell
ab -c 500 -t 360 http://internal-ec2-instance.mycompany.com/helloworld-static/index.html
```

The above test achieved over 12000 requests/second. I’m sure it doesn’t fully eliminate Nginx as a possible root cause, but at least we can see that the host in general is capable of much higher throughput.

Other configuration variations I have tried, with similar results, include:
•	Disable keepalive in nginx.conf
•	Set keepalive to 60 in nginx.conf
•	Unset multi_accept in nginx.conf
•	Use ManagedFastCgiListener with CombinedFastCgiListenerTransport and CombinedAppHostTransport in HFC config.

I have tried relevant suggestions already posted here, including this: https://github.com/xplicit/HyperFastCgi/issues/23

I’ll confess that I’m new to Nginx+FastCGI configuration, and fairly new to Mono.

Unfortunately, I’m basically stuck. Any suggestions are welcome. 

Thanks in advance, and kind regards, Matt

**Comment by xplicit** [comment]
What is the HelloWorld application you used to  check the performance? 

500 reqs/second is very low throughput for HelloWorld.app with native listener. Accordingly to your nginx static file tests you should get 1.2-1.3K rps for ASP.NET WebForms app and 2.3-2.5K if you use servicestack for REST.

For benchmarking you should disable logging in nginx (disable access log) and in hyperfastcgi (set the logging levels to error only and please check that hyperfastcgi logs don't contain errors). And please check that the app returns the page you've expected (if the page returns an ASP.NET error message instead, the performance could be very low). 

Also it would be interesting to see benchmarking results for Raw Host https://github.com/xplicit/HyperFastCgi/blob/master/samples/hello-world.config

I've made the tests before for ServiceStack helloworld app and WebForms helloworld app, running 100 millions requests without degrading performance, so I think the issue possible in the exceptions were throwed during the benchmarking or in the specific application code.

**Comment by matsaleh13** [comment]
Thanks for your quick reply!

I agree that 500 reqs/sec is very low; thanks for confirming that. The expected performance you suggest is what I also had expected, between 1K - 2.5K depending on various other factors.

We have a custom ASP.NET framework upon which we are building a suite of web "micro" services. It is similar in nature to ServiceStack as far as I know. Our HelloWorld is a reference implementation of one such service. 

The request being tested is a trivial "echo". The service responds with a raw string, the contents of the last segment of the request's URL. In all my tests, this is simply the string "test". I have verified during testing that the app returns the expected string "test".

I will try adjusting the log output as you suggest in both nginx and hyperfastcgi. 

I have not found any evidence of exceptions being thrown in our service code. If they are, they are being silently ignored (obviously horrible if so, I'll verify).

As part of my performance analysis, I profiled our HelloWorld service running under HyperFastCgi while running one of our ab tests. Perhaps you could gain some insight from it, and make some suggestions. Please see the mprof report below, where I have marked lines of interest with asterisks (**):
```C#
Method call summary
Total(ms) Self(ms)      Calls Method name
 1225084      180      69274 (wrapper runtime-invoke) <Module>:runtime_invoke_void__this___object (object,intptr,intptr,intptr)
**887436   887436      92455 (wrapper managed-to-native) System.Threading.WaitHandle:WaitOne_internal (System.Threading.WaitHandle,intptr,int,bool)
  850860      131      47376 System.Threading.WaitHandle:WaitOne (int,bool)
  845852       23      23856 (wrapper runtime-invoke) object:runtime_invoke_void__this__ (object,intptr,intptr,intptr)
  845605        4          2 System.Threading.Thread:StartInternal ()
  845600      222          2 System.Threading.Timer/Scheduler:SchedulerThread ()
  844845       20      45041 System.Threading.WaitHandle:WaitOne (int)
  644640       49      22546 HyperFastCgi.Transports.BaseAppHostTransport/<AddBodyPart>c__AnonStorey0:<>m__1 (object)
  644591       45      22546 HyperFastCgi.AppHosts.AspNet.AspNetNativeWebRequest:Process (HyperFastCgi.Interfaces.IWebResponse)
  644545       36      22546 HyperFastCgi.AppHosts.AspNet.MonoWorkerRequest:ProcessRequest ()
  644484       59      22546 System.Web.HttpRuntime:ProcessRequest (System.Web.HttpWorkerRequest)
  643917       89      22546 System.Web.HttpRuntime:RealProcessRequest (object)
**643365      151      22546 System.Web.HttpRuntime:Process (System.Web.HttpWorkerRequest)
**558696      112      22546 System.Web.HttpApplication:System.Web.IHttpHandler.ProcessRequest (System.Web.HttpContext)
  557503        0          1 (wrapper runtime-invoke) <Module>:runtime_invoke_int_object (object,intptr,intptr,intptr)
  557503        9          1 HyperFastCgi.MainClass:Main (string[])
  556055        0          1 HyperFastCgi.Listeners.NativeListener:<Listen>m__0 (object)
  556055   548848          1 (wrapper managed-to-native) HyperFastCgi.Listeners.NativeListener:ProcessLoop ()
  556046        0          1 Mono.Unix.UnixSignal:WaitAny (Mono.Unix.UnixSignal[])
  556046        0          1 Mono.Unix.UnixSignal:WaitAny (Mono.Unix.UnixSignal[],int)
  556046   556044          1 (wrapper managed-to-native) Mono.Unix.UnixSignal:WaitAny (intptr[],int,int,Mono.Unix.UnixSignal/Mono_Posix_RuntimeIsShuttingDown)
  521490       80      22546 System.Web.HttpApplication:Start (object)
**511079     1340      39825 System.Web.HttpApplication:Tick ()
**509734     1081      39825 System.Web.HttpApplication/<Pipeline>c__Iterator1:MoveNext ()
**467888      126      22546 MyCompany.RpcServer.Web.RpcAsyncHandler:BeginProcessRequest (System.Web.HttpContext,System.AsyncCallback,object)
**467613     1116      35328 MyCompany.RpcServer.Web.RpcAsyncHandler/<ProcessRequestAsync>c__async0:MoveNext ()
  465738       35      22546 MyCompany.RpcServer.Web.RpcAsyncHandler:ProcessRequestAsync (System.Web.HttpContext)
  465530       52      22546 System.Runtime.CompilerServices.AsyncTaskMethodBuilder:Start<MyCompany.RpcServer.Web.RpcAsyncHandler/<ProcessRequestAsync>c__async0> (MyCompany.RpcServer.Web.RpcAsyncHandler/<ProcessRequestAsync>c__async0&)
  338794      133     157944 System.Collections.Specialized.NameValueCollection:get_Item (string)
  335142       30      22546 System.Web.HttpParamsCollection:Get (string)
  332980       66      22546 System.Web.HttpParamsCollection:MergeCollections ()
**332878     1827      67663 System.Collections.Specialized.NameValueCollection:Add (System.Collections.Specialized.NameValueCollection)
**253109     5170    2299694 System.Collections.Specialized.NameValueCollection:Add (string,string)
**214610     6754    8169150 System.Collections.Hashtable:GetHash (object)
**201955    37328    6786215 System.Web.Util.SecureHashCodeProvider:GetHashCode (object)
  191292      945    2119262 System.Web.BaseParamsCollection:LoadInfo ()
  182019       46      22546 System.Web.BaseParamsCollection:get_Count ()
  181926       33      22546 System.Web.ServerVariablesCollection:InsertInfo ()
  181893     1016      22546 System.Web.ServerVariablesCollection:loadServerVariablesCollection ()
**164644   106191   83410743 char:ToLower (char,System.Globalization.CultureInfo)
**161323     6469    2324869 System.Collections.Specialized.NameObjectCollectionBase:BaseAdd (string,object)
  151755     5203    5785464 System.Collections.Hashtable:get_Item (object)
```

I have not yet tried printing traces from this report, but I think I'll take a stab at that for some of these calls.

Thanks again for your help, and best regards.

**Comment by matsaleh13** [comment]
Sergey,

I want to thank you again very much for your time. 

After reading your comments about HelloWorld, I decided to write a truly trivial implementation that does not use our service framework at all to use as a baseline. I reran my test suite against the new trivial service running under HyperFastCgi, and this time I got the expected results: approximately 2400 requests/second at concurrency 20 with no degradation over time.

I apologize for wasting your time, but thank you very much for helping me scope my investigation more precisely.

Kind regards, Matt

**Comment by xplicit** [comment]
Glad to hear that! By the way from your profiling traces I suspect that you've run into threadpool strarving when threads don't return to the threadpool after assigning by asynchronous task. This is just an idea I can't be sure 100% in it.  You can proof or overturn my suspection  by watching number of threads in threadpool (via performance counter, for example). Also if I am right about threadpool starving, increasing `min-threads` value in  hyperfastcgi config should decrease degradation.

**Comment by matsaleh13** [comment]
Thanks very much for that observation and suggestion! For the near term we've got a non-async implementation that provides reliable behavior and acceptable results for now. We'll want to revisit async soon enough, however, so I'll be sure to keep your suggestion in mind when I come back to that.

Thanks and regards, Matt
