### ISSUE TITLE
Large responses with native transport again

### ISSUE THREAD

**Issue by vadimwind** [xplicit/HyperFastCgi#29]
Alt Linux 7.0.5 - Nginx 1.7.11 - Mono 3.12.1 - last HyperFastCGI from sources
Configuration is from issue #24

It seems that problem with lange responses still exists.

Steps for reproduce:
1. Run the large test.aspx (~60kb)
https://drive.google.com/file/d/0B3W5PyVh7-kXMzF3SHlSZ2JTMkE/view?usp=sharing
2. Refresh page in your browser 10-20x times

Sometimes error will occur:
libev.c:322: cmd_error():	A socket error (0x21) occurred on fd 14.
libev.c:180: shutdown_cmdsocket():	Error shutting down client connection on fd 14: 107 (Конечная точка передачи не подсоединена)

Nginx log:
2015/04/23 18:42:08 [crit] 14492#0: *2820 open() "/usr/local/nginx/fastcgi_temp/1/27/0000000271" failed (13: Permission denied) while reading upstream, client: 192.168.68.11, server: foxtrot, request: "GET /test.aspx HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "..."

**Comment by xplicit** [comment]
I could not reproduce it yet. The error means "Unrecoverable error while reading", but have no idea what can be a cause of the issue.  And very strange permission denied message in nginx.  Can the operating system drop the connections between nginx and hfc by some reason?

**Comment by xplicit** [comment]
Here the working sample of getting the page from Ubuntu 14.04 64-bit. Need more info to investigate the issue.

     ab -n 1000 -c 20 http://104.238.167.177:81/test1.aspx

**Comment by xplicit** [comment]
As @vadimwind said in chat the issue was in incorrect nginx permissions to `/usr/local/nginx/fastcgi_temp/` temp files. After correcting permissions the issue has gone.  Reference http://www.nginxtips.com/13-permission-denied-while-reading-upstream-using-nginx/ for more info.
