### ISSUE TITLE
Build on Mono 4.0

### ISSUE THREAD

**Issue by cvetomirtodorov** [xplicit/HyperFastCgi#30]
I upgraded mono to 4.0 because there are a few bugs fixed there which help me. Problem is that it drops support for .net 2.0 and 4.0 and (at least I think that's the reason) I cannot compile HFCGI because there is no `gmcs` (running `./autogen.sh --prefix=/usr` reports that). Here are the release notes: http://www.mono-project.com/docs/about-mono/releases/4.0.0/

Any hints how to build HFCGI with mono 4.0?

**Comment by xplicit** [comment]
Fixed in https://github.com/xplicit/HyperFastCgi/commit/27ebd80a0a7b2a435d2954613b8a58fb9edb3044

**Comment by firstfocus** [comment]
Hello,
I've got Mono installed from the repo Mono JIT compiler version 4.0.1 (tarball Tue Apr 28 11:47:58 UTC 2015)
I'm sure I've got the right version from GIT with this fix but I'm getting this error on make:
make[3]: Entering directory `/opt/HyperFastCgi/src/HyperFastCgi/scripts'
make[3]: *** No rule to make target `hyperfastcgi2', needed by `all-am'.  Stop.

./autogen.sh --prefix=/usr reports this, with missing 2.0 as expected:
Mono 2.0 compiler:       not found
Mono 4.0 compiler:       /usr/bin/dmcs
It could be me, but any ideas what might be wrong?

**Comment by xplicit** [comment]
Which operating system do you use? What is the output of `Target frameworks` after running`./autogen.sh --prefix=/usr`?

**Comment by firstfocus** [comment]
Hi Sergey,

Thanks for the fast reply. Sorry should have mentioned. Ubuntu 14.04.2 LTS.
This is the ouput of autogen:
hyperfastcgi-0.4

  Build Environment
    Install prefix:          /usr
    Datadir:                 /usr/share
    Libdir:                  /usr/lib
    Build documentation:
    Mono 2.0 compiler:       not found
    Mono 4.0 compiler:       /usr/bin/dmcs
    Target frameworks:       .NET 4.0

2015-05-01 15:48 GMT+02:00 Sergey Zhukov <notifications@github.com>:

> Which operating system do you use? What is the output of Target frameworks
> after running./autogen.sh --prefix=/usr?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/xplicit/HyperFastCgi/issues/30#issuecomment-98138525>.
>



-- 
Met vriendelijke groet,
Menno Flikkema

f i r s t f o c u s   b v
Weverstede 19 3431 JS Nieuwegein Netherlands

office:             +31 30 737 06 76
marketing:      +31 30 737 06 77

internet:          www.firstfocus.eu

**Comment by xplicit** [comment]
What the output you've got if run
    
    make clean
    ./autogen.sh --prefix=/usr
    make

?

**Comment by xplicit** [comment]
If this doesn't help as a workaround you can edit the file

https://github.com/xplicit/HyperFastCgi/blob/master/src/HyperFastCgi/scripts/Makefile.am#L26

delete line 13 and 18
and removing the hyperfastcgi2 occurrences from line 26 and line 30.

**Comment by firstfocus** [comment]
Got this again after the make clean:

Making all in scripts
make[3]: Entering directory `/opt/HyperFastCgi/src/HyperFastCgi/scripts'
make[3]: *** No rule to make target `hyperfastcgi2', needed by `all-am'.  Stop.
make[3]: Leaving directory `/opt/HyperFastCgi/src/HyperFastCgi/scripts'
make[2]: *** [all-recursive] Error 1

Your workaround dit it though, now running again. Many thanks, your work on HyperFastCgi is much appreciated!

**Comment by xplicit** [comment]
Some additional info about the issue.
It compiles on Ubuntu 14.04, but compilation fails with the error mentioned above on Travis CI which is Ubuntu 12.04 AFAIK.

**Comment by xplicit** [comment]
This commit fixes the last error
https://github.com/xplicit/HyperFastCgi/commit/d270157ac274cea0b70a893d085db30ea581b4b7
