### ISSUE TITLE
Unix sockets Permissions

### ISSUE THREAD

**Issue by ivanovnikolay** [xplicit/HyperFastCgi#34]
Hello, @xplicit , cool project!
Is it possible to specify the permissions for unix socket?
Like this:
<code>
    ...
    &lt;address&gt;//775@/tmp/onlyoffice.socket&lt;/address&gt;
    ...
</code>

**Comment by xplicit** [comment]
There is no option to set up permission explicitly in hyperfastcgi config. But if you trying to avoid 'permission denied' issue when restarting nginx/hyperfastcgi  this comment might help you.

https://github.com/xplicit/HyperFastCgi/issues/16#issuecomment-57070579

**Comment by ivanovnikolay** [comment]
Thank you!
