### ISSUE TITLE
What's the correct way to build with Mono 4?

### ISSUE THREAD

**Issue by derFunk** [xplicit/HyperFastCgi#41]
When running ./autogen.sh on a Linux system equipped with Mono4, the following error occurs:
> checking for gmcs... no
> configure: error: You need to install 'gmcs'

That's okay because *mcs is deprecated in Mono 4.
I can see in the makefiles that building with Mono 4 (xbuild to receive mono-server-hyperfastcgi4.exe) is supported, but what is the right way to trigger a Mono 4 only build with ./autogen.sh - instead of manually issuing xbuild and taking care of the rest which the build+install scripts do automatically?

(Oh, and I'm on the v0.3 stable branch).

Thanks.

**Comment by xplicit** [comment]
Fixed by https://github.com/xplicit/HyperFastCgi/commit/392064ff7261dc00c65745e0f4a4f857e1076064
