### ISSUE TITLE
Provide sample init.d auto-run with automatic .webapp read.

### ISSUE THREAD

**Issue by junalmeida** [xplicit/HyperFastCgi#51]
It would be nice to have some init.d to autorun service, with options to run under www-data, automatic reload after dir of webapp's changes, one process per webapp file (similar iis pool config).

**Comment by xplicit** [comment]
In Progress. At first there will be version for one process, then I'll see what can be done additionally to provide autostart for several hyperfastcgi processes (like application pools)

**Comment by xplicit** [comment]
Fixed via https://github.com/xplicit/HyperFastCgi/commit/8ba103a6fb61caabe5c1fa81530dc98353aca7ad

There are two files: init.d script itself and `install-service.sh` script for Ubuntu.

tested with Ubuntu 14.04 and Ubuntu 15.10

**Comment by junalmeida** [comment]
Thank you, going to test soon.
