### ISSUE TITLE
Better explanation of <root-dir>

### ISSUE THREAD

**Issue by junalmeida** [xplicit/HyperFastCgi#53]
Is this server.config option for searching for .webapps ? Or is this just a shortcut for a webapp configured to '/'?

**Comment by xplicit** [comment]
It has the same meaning like `--root` option in XSP. When you set `root-dir` you can use relative paths to this root in application definitions.

http://manpages.ubuntu.com/manpages/dapper/man1/xsp.1.html

     --root PATH
              The  root directory for XSP.  The default is the directory where
              XSP is executed. The current directory will be changed  to  this
              one  before  creating  any  application.   AppSettings key name:
              MonoServerRootDir
