### ISSUE TITLE
Using ThreadPool is slower than Task

### ISSUE THREAD

**Issue by derFunk** [xplicit/HyperFastCgi#61]
I'm still doing performance tests regularly and wanted to let you know that using `<multithreading>ThreadPool</multithreading>` is performing 20-50% slower in average than `<multithreading>Task</multithreading>` with our real life user session load test setup.

I had expected that ThreadPool would be actually faster than Task. 
What do you think about Task vs. ThreadPool performance comparison?

**Comment by xplicit** [comment]
It depends on code in your app, how it uses ThreadPool or Tasks, which task schedulers it uses an so on.  I did not see that ThreadPool in general is slower or faster then Task, they perform both near the same speed, so you have to make performance metrics for your app and choose the best configuration (or optimize the bottlenecks in the app if possible)
