### ISSUE TITLE
Nginx + HyperFastCgi + ServiceStack multiple services

### ISSUE THREAD

**Issue by Ravenheart** [xplicit/HyperFastCgi#62]
Greetings,

I am trying to host multiple web services with only one domain/ip. Specifically what I want to end up with is this:

http://192.168.1.105/service1
http://192.168.1.105/service2
http://192.168.1.105/service3

All the configurations I've read either use multiple domains or sub-domains or different ports. Can you please give a sample HFC config that would correctly handle multiple services in different paths. (A Nginx config would also be nice, although not critical).

**Comment by xplicit** [comment]
You need to define multiple `web-application` elements inside `web-applications` element. Here is documentation
https://github.com/xplicit/Hyperfastcgi#web-applications-element

Sample:
https://github.com/xplicit/HyperFastCgi/blob/master/samples/combined-two-apps.config
