### ISSUE TITLE
Adding --server flag to mono/HFC start script

### ISSUE THREAD

**Issue by derFunk** [xplicit/HyperFastCgi#64]
Hi,

when creating /usr/bin/hyperfastcgi, maybe `--server` should be a option set by default.

From the manpages:
```
--server
              Configures the virtual machine to be better suited for server operations (currently, allows a heavier threadpool initialization).
```

**Comment by xplicit** [comment]
Maybe I missed something, but it looks that `--server` option is not used at all in mono. I found this commit https://github.com/mono/mono/commit/26d0b81c266f87df259ccb297bc22d60768e2e72 for `--server` flag, but the code was removed when mono changed threadpool model to MS .NET ThreadPool.
