### ISSUE TITLE
Seeing requests with about 46k of request body data fail with 502 under mono-server-hyperfastcgi4

### ISSUE THREAD

**Issue by jpasichnyk** [xplicit/HyperFastCgi#67]
Hosted behind nginx with unix socket.  Same server, mono webservice but with fastcgi-mono-server4 works fine, but when hosted with hyperfastcgi I'm getting the 502's.  Any ideas?  Variables i need to tune in HFCGI?

Not seeing any logs/console output from nginx/hyperfastcgi that give any hit of an issue. :(

Running Mono.WebServer.HyperFastCgi.exe 0.3.4.0 (Looks like compile date was Dec 2015), I'll try recompiling and repro on latest .3 stable.

**Comment by xplicit** [comment]
@jpasichnyk Use v0.4 - this build is recommended to use with latest build of mono. You can try it also using docker container: https://hub.docker.com/r/xplicit/hyperfastcgi/

**Comment by jpasichnyk** [comment]
@xplicit i don't see a branch/tag for .4, assuming this is just master and a moving target?  It is "stable" though?

**Comment by xplicit** [comment]
Yes, it's master branch and it's stable.
