### ISSUE TITLE
Will HyperFastCgi support .NET Core (ASP .NET 5)?

### ISSUE THREAD

**Issue by derFunk** [xplicit/HyperFastCgi#68]
Can something be said about this already?

When porting existing web apps to .NET Core, should we stick with Kestrel?

**Comment by xplicit** [comment]
Kestrel is targeted to be highly-optimized server for .NET Core. The large team in MSFT works on making .NET Core and Kestrel server run fast and reliable. So I don't see any point to port HyperFastCgi to .NET Core. HyperFastCgi was created as replacement to slow mono fasctgi server for hosting classic ASP.NET apps. But .NET Core does not support `System.Web`, so I don't see why HyperFastCgi can be useful in this area. Only if port System.Web to .NET Core :) But it's a quite large job and doing it as a hobby project like HyperFastCgi looks for me quite problemastic.
