### ISSUE TITLE
hyperfastcgi stop working but not crash

### ISSUE THREAD

**Issue by antonheryanto** [xplicit/HyperFastCgi#69]
Thank for the project, 
recently just deploy at university production server running legacy ASP.NET MVC 4 with traffics 100 - 300 rps with 30k uniques visitor perday.
its performs ways better than mono fastcgi, but has lots of caveats. I have trying with multiple configuration variant.  following is the server information
```
OS: Opensuse Tumbleweed
Mono JIT compiler version 4.8.0 (mono-4.8.0-branch/d6fdb01 Tue Oct 18 03:17:51 MYT 2016)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	LLVM:          supported, not enabled.
	GC:            sgen
 ```
running compiled hyperfastcgi master branch.
with hyperfastcgi.config
```xml
<configuration>
  <server type="HyperFastCgi.ApplicationServers.SimpleApplicationServer">
    <host-factory>HyperFastCgi.HostFactories.SystemWebHostFactory</host-factory>
    <threads min-worker="200" max-worker="0" min-io="100" max-io="0" />
  </server>
  <listener type="HyperFastCgi.Listeners.NativeListener">
    <apphost-transport type="HyperFastCgi.Transports.NativeTransport">
      <multithreading>Single</multithreading>
    </apphost-transport>
      <protocol>InterNetwork</protocol>
      <address>127.0.0.1</address>
      <port>9001</port>
  </listener>
    <apphost type="HyperFastCgi.AppHosts.AspNet.AspNetApplicationHost">
    <log level="All" write-to-console="true" />
    <add-trailing-slash>false</add-trailing-slash>
    </apphost>
    <web-applications>
      <web-application>
        <name>app</name>
        <vhost>app</vhost>
        <vport>80</vport>
        <vpath>/</vpath>
        <path>/path/to/app</path>
      </web-application>
    </web-applications>
</configuration>
```
nginx.conf
```nginx.conf
upstream hf {
  #server unix:/tmp/hf.sock;
  server 127.0.0.1:9001;
  server unix:/tmp/mf.sock backup;
  keepalive 30;
}
```

first the running process fill up with this warning/debug message, but my impression  its just for debuging purpose (it is?)
```
libev.c:317: cmd_error():        Remote host disconnected from fd 49
libev.c:322: cmd_error():        A socket error (0x21) occurred on fd 54.
libev.c:180: shutdown_cmdsocket():        Error shutting down client connection on fd 54: 107 (Transport endpoint is not connected)
```
but my worry is the stability which quite bad which had lot of crash on heavy traffics sometimes each half or an hour. I have trying multiple combination of configuration but has its own problems. my conclusion so far, the NativeListener multithreading type of threadpoll and task tend to crash often because of Native stacktrace, possible threadpool implementation compatibility  issue with current Mono version have trying mono stable 4.6.1 and ustable 4.8.0 but had similar experience.
which i think related to issue #33:
```
Native stacktrace:
at (wrapper managed-to-native) HyperFastCgi.Listeners.NativeListener:Listen (uint16,string,uint16)
at HyperFastCgi.Listeners.NativeListener.Listen () [0x00065] in <7f8adb1df567467997e8ac48a480b802>:0
at (wrapper managed-to-native) HyperFastCgi.Listeners.NativeListener.ProcessLoop () <0x00059>
at HyperFastCgi.Listeners.NativeListener.<Listen>m__0 (object) <0x0000b>
```
 Multithreading single mostly most stable which crash after 6 to 10 hours. Tcp socket more stable but the Unix socket got error of the socket already in uses when process crash or restart even though the permission is correct. uses #16 workaround not worked.
```
libev.c:493: Listen():        Error binding listening socket: 98 (Address already in use)
```
But the major concern is, even with this all of this crash, its not really much problem as can be fix along the way (will find the time to learn and try submit pull request if possible 😅 ), as the old mono fastcgi mostly crash and restart few time under high load. but its better in term of stability because when crash systemd can restart the process and apps can be run normally. but hyperfastcgi just stop working but the process didn't crash which lead the process runing but application is in fail state. Native stacktrace will return 502, which acceptable. but using mutlithreading single process just stop working and produce this error message bellow 
```
fcgi-transport.c:399: parse_params():        Can't find app! HOST='myapp.com' port=80 path='/'
```
which also not crash but process not working as expected and systemd can't help to restart the process.

So I would like to knows which part of code i need to venture to fix the quick workaround where the hyperfastcgi process will throw exception so systemd can send HUP signal or restart the process, when native stacktrace happen or the process trigger 404 can't find app (which means app information can't be parse).

Thank you for your works and time, would to hear from soon

**Comment by antonheryanto** [comment]
Forgot to mention.
in old mono fastcgi got this warning/error Duplicate name, HTTP_COOKIE, encountered. Overwriting existing value (didn't know where its came). which might related #42 but as see the fix only applied to branch v0.3_stable

**Comment by xplicit** [comment]
What is the `libevent` version on your operating system? `A socket error (0x21) occurred on fd 54` is not a normal error message which should not appear in logs (while `Remote host disconnected from fd 49` can appear when client closes the page before request is processed).

Do you have requests which take large amount of time? In this case you should add `fastcgi_read_timeout` with large value (in seconds) to not break upstream connection, while request is processed.

Can you try run your app in docker instance? https://hub.docker.com/r/xplicit/hyperfastcgi/ 
It helps to isolate OS/configuration issues and check if problem exists in known working configuration.

Anyway if after these changes you still have issues with native listener, you can switch to `ManagedListener` with `Combined` (managed + native) or `Managed` transport. With your number of requests (100-300 rps) you should not get downgrading in performance. Sample configs are available in `samples` directory.

#16 workaround I tried on Ubuntu and did not check if it works on other operating systems.

You are lucky if `mono-server-fastcgi` just crashed after some working time. In my experience it tried to eat all existing memory than hang with 100% of CPU usage and stopped to process any requests from the clients. That's why I started to write my own implementation of fastcgi server.

**Comment by antonheryanto** [comment]
Thank you very much for your quick response, appreciate
following are the libevent information when hyperfastcgi start:
```sh
libev.c:461: Listen():        libevent version: 2.0.22-stable
libev.c:475: Listen():        libevent is using epoll for events.
```

the application is e-learning platform which handle lots of files upload with max upload size 300MB with students uploading from slow connection may explain lot of timeout, as your suggestion i have set fastcgi_read_timeout 600; will report later effect on when traffic is high as on my timezone now early in morning UTC+8

will try later running the apps on docker, now seem not an options because of complexity with legacy application.

i have try using ``ManagedListener`` but still crash quite often, but will try again later after inspect the effect on fastcgi_read_timeout and reduced possiblility  of following errors happen:
```
fcgi-transport.c:399: parse_params():        Can't find app!
```
how to prevent its happen, as its cause headache 😅 as the process running but application state is broken. lately the hyperfastcgi running quite stable and longer, but when that error happen from user perspective the application is crash but process is running, but the only cure to the problem is restart the service. so how to prevent this ever happen or lets hyperfastcgi restart when this errors happen.  The error not a 5xx error, is it trigger 404 to nginx?. a part from this errors, the hyperfastcgi perform really well on cpu and memory usage. appreciate your time, thank very much

**Comment by antonheryanto** [comment]
further diagnose on socket timeout, from nginx log seem the user try upload file more then 300mb sometimes over 1gb event already state max upload 300mb, but nginx didn't prevent the request to happen until user finish send upload and pass it to fastcgi which might cause socket timeout.

i have reconfigure nginx to prevent it happen based on http://stackoverflow.com/questions/4947107/nginx-upload-client-max-body-size-issue answer 
```nginx.conf
 client_body_in_file_only clean;
 client_body_buffer_size 32k;
 client_max_body_size 300m;
 sendfile on; 
 send_timeout 300s;
``` 
will diagnose the effect

**Comment by antonheryanto** [comment]
its happen again
```
hyperfastcgi4[22289]: host-list.c:55: unregister_host():  app:80:/:/srv/www/htdocs/myApp/MyApp
fcgi-transport.c:399: parse_params():  Can't find app! HOST='myapp.com' port=80 path='/'
```
and backup service in nginx upstream not triggered to take place as the hyperfastcgi just return not found error and actually broken or crash
```
upstream hf {
  server 127.0.0.1:9001;
  server unix:/tmp/mf.sock backup;
  keepalive 30;
}
```

when restarted the service this error found
```
mono[17070]: g_hash_table_lookup: assertion 'hash_table != NULL' failed
mono[17070]: g_hash_table_insert_internal: assertion 'hash_table != NULL' failed
mono[17070]: g_hash_table_lookup: assertion 'hash_table != NULL' failed
mono[17070]: g_hash_table_insert_internal: assertion 'hash_table != NULL' failed
mono[17070]: g_hash_table_lookup: assertion 'hash_table != NULL' failed
```

any chance this happen because i have nested folder which handle by php-fpm fastcgi ?
btw to instruct hyperfastcgi to return error or exception when unregister_host() happen so backup service can take over. i thing is preferable as reduce possible gotcha handle kind of this error

**Comment by antonheryanto** [comment]
and also got nested aspx page for tinymce filemanager plugin which nested inside mvc folder, are these contributes to possible problem?

**Comment by xplicit** [comment]
Do you have some processes which send KILL signal to hyperfastcgi? Maybe some cron job which do this on regular basis?

If not, this possible could happen if web application in domain is crashed or recycled. I did not check yet, but this workaround might work (add at the end of `OnHostUnload` method) https://github.com/xplicit/HyperFastCgi/blob/master/srcHyperFastCgi/Transports/NativeTransport.cs#L19


     if (!isShutdown) 
         	RegisterHost (host.VHost, host.VPort, host.VPath, host.Path);

I will check this case of AppDomain recycling more detaily on weekend, but if workaround mentioned above does not work as is you can temporary add  `Environment.Exit(0);` in `OnHostUnload` to kill the whole process when domain is unloaded.

**Comment by antonheryanto** [comment]
Thank for your response,
I did have cronjob which restart hyperfastcgi service which run at 4 am (once a day) to make sure if hyperfastcgi hang/unload  service is restart so it can properly worked again (which i did because prossible unload happen). but the unload/unregister happen mostly on peak hours mostly twice a day now which i think not related to that cron job which restart systemd service.

i have patch the NativeTransport OnHostUnload
```csharp
protected override void OnHostUnload (IApplicationHost host, bool isShutdown)
{
    Logger.Write (LogLevel.Debug, "unregister Host when domain has problem");
    UnregisterHost (
        host.VHost,
        host.VPort,
        host.VPath
    );
    if (!isShutdown) {
         RegisterHost (host.VHost, host.VPort, host.VPath, host.Path);
         Logger.Write (LogLevel.Debug, "Register Host when not not shutdown");
     } else {
         Logger.Write (LogLevel.Debug, "Exit process when shutdown");
         Environment.Exit(0);
     }
}
```
will see the effect

**Comment by xplicit** [comment]
This commit should fix the issue. Could you check with new build?

https://github.com/xplicit/HyperFastCgi/commit/06d416c829766131bf17ccd4c0f006af370666d3

**Comment by antonheryanto** [comment]
Thanks for the quick fix,
previous workarounds are successful as when unregister_host happen its re-register again and exit process never triggered.

I have pull and build the fix and will report the outcome.

**Comment by antonheryanto** [comment]
after 24+ hours monitoring, i can confirm the host unregister issue solved as when its happen hyperfastcgi re-register again as shown in logs below:
```
Debug   AppHostBase.OnDomainUnload
Debug   Calling HostUnload event handler, num events=2
Debug   Unloading ApplicationHost domain, isShutdown=False
parse_params():        Can't find app!
parse_params():        Can't find app!
parse_params():        Can't find app!
parse_params():        Can't find app!
parse_params():        Can't find app!
parse_params():        Can't find app!
Debug   Register native transport
Debug   Configuring ApplicationHost
Debug   Configured host in domain 1de0ba32, id=2
unregister_host()
register_host()
```
so i close this issues, thank you very much for your quick response
