### ISSUE TITLE
Similar issue with #67, 502 after 50k requests

### ISSUE THREAD

**Issue by andreyie** [xplicit/HyperFastCgi#76]
Nginx comunicates with HyperFastCgi by TCP keepalive connection, after around 50k requests gettings 502 error. In HyperfastCgi log no errors, Version of HyperFast is  0.4.4.0, mono is 3.2.8. What can be the cause?

**Comment by andreyie** [comment]
Что это я, на русском ведь можно.
Приветсвую, проблема описана выше, для веб приложения использую servicestack, получаю 502 ошибку не всегда после 50к запросов, бывает и на 20.

**Comment by andreyie** [comment]
Первые два конфига это nginx вторые два для HyperFastCgi:

[server.conf.txt](https://github.com/xplicit/HyperFastCgi/files/648353/server.conf.txt)
[nginx.conf.txt](https://github.com/xplicit/HyperFastCgi/files/648358/nginx.conf.txt)
[hyperfast_server.config.txt](https://github.com/xplicit/HyperFastCgi/files/648371/hyperfast_server.config.txt)
[hyperfast_app.config.txt](https://github.com/xplicit/HyperFastCgi/files/648372/hyperfast_app.config.txt)

**Comment by xplicit** [comment]
`keepalive` в конфиге nginx должно быть чуть меньше, чем количество `threads min-worker` в конфиге hyperfastcgi и обязательно должно быть меньше чем `threads max-worker`.  При данных значениях threads "90,0,24,0" `keepalive` должно быть около 80

Также необходимо обновить mono. 3.2.8 - очень старая версия и она может быть источником проблем.

Сколько ядер на сервере? Какая версия ServiceStack используется? Какая строка запуска hyperfastcgi? Что выдает hyperfastcgi в консоль? Что в логах nginx во время ошибок 502?

502 ошибка возникает на каждом запросе после 50К запросов или лишь на некоторых запросах? Также может быть в каком-нибудь сервисе deadlock, который блокирует threads и из-за этого после продолжительной работы свободных threads не остается. Чтобы это проверить, необходимо настроить counters, которые следят за threadpool и понаблюдать за ними в процессе выполнения.

**Comment by andreyie** [comment]
Проблема была в конфигурировании HyperfastCgi, заменил NativeListener на ManagedFastCgiListener, всё заработало, спасибо Сергею за помощь
