### ISSUE TITLE
configfile difficult to use

### ISSUE THREAD

**Issue by jradxl** [xplicit/HyperFastCgi#80]
Like Xsp4 it's possible to add command line options into a configuration file.
This is good when using Systemd as systemctl daemon-reload is then not necessary as editing command line options in hyperfastcgi.service is then not needed.

However, the configfile is a little different to Xsp4's.
In fact all the properties need to be present, and a null xml file needed if not using appconfigfile and appconfigdir. Furthermore, the Type of the property needs to be included.

Here is an example

```
<?xml version="1.0" encoding="UTF-8" ?>
<Settings>
    <!-- It is necessary to include all the Options -->
	<Setting Name="applications"  Type="string" Value="/:/var/www" />
	<Setting Name="logfile"       Type="string" Value="/var/log/hyperfastcgi/hfc.log" />
	<Setting Name="loglevels"     Type="string" Value="All" />
	<Setting Name="printlog"      Type="Bool"   Value="True" />
	<Setting Name="verbose"       Type="Bool"   Value="True" />
	<Setting Name="root"          Type="string" Value="/var/www" />
	<Setting Name="socket"        Type="string" Value="tcp:127.0.0.1:9020" />
	<Setting Name="appconfigfile" Type="string" Value="/etc/hyperfastcgi/nullxmlfile.config" />
	<Setting Name="appconfigdir"  Type="string" Value="/etc/hyperfastcgi/nullxmlfile.config" />
	<Setting Name="stoppable"     Type="Bool"   Value="True" />
</Settings>
```

I'm sorry if I've missed mention of this in your documentation/ I'm sure this isn't mentioned.
If I'm right, perhaps you'd like to include something similar.
If it's something you weren't intending to support, do please ignore my comments.
Thanks very much for this interesting alternative to fastcgi-mono-server.

**Comment by xplicit** [comment]
There is already config file which supports most of the command line options. How to use it with descriptions of all [config options](https://github.com/xplicit/HyperFastCgi/blob/master/README.md#config-file-parameters) you can find in [README.md](https://github.com/xplicit/HyperFastCgi/blob/master/README.md#arguments). Also you can look at config [samples](https://github.com/xplicit/HyperFastCgi/tree/master/samples), and sample scripts for ubuntu [init.d, systemd and upstart](https://github.com/xplicit/HyperFastCgi/tree/master/samples/ubuntu-startup)
